### PR TITLE
Add support for LCDParameters and vocabulary file

### PR DESCRIPTION
**Pull request by marcusabate**
Adds commandline flags for loop closure detector related files.

We can merge this to master after `feature/loop_closure` on VIO is merged to master.

Note that these changes will need to be ported to the `devel` branch.

### CODE REVIEW

**Comment by marcusabate** [comment]
Chose to keep my changes on the `experiments/jenkins_euroc.yaml` file since we currently don't have a solution for using `pipeline_types` with VIO parameters.

**Comment by marcusabate** [comment]
@ToniRV if we can merge this then Kimera-VIO can use master instead of this branch.

**Comment by ToniRV** [comment]
Would have been nicer to keep evaluation_lib smaller rather than bigger, but merging for now

**Comment by marcusabate** [comment]
Yeah I plan on doing a major refactoring of this at some point, my solution was pretty hacky and doesn't look nice.

**Pull request merged**
